# Generated by Django 4.2.5 on 2026-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GachaDrawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cost_primary",
                    models.PositiveIntegerField(verbose_name="消耗一级货币"),
                ),
                (
                    "reward_secondary",
                    models.PositiveIntegerField(verbose_name="获得二级货币"),
                ),
                ("multiplier", models.PositiveIntegerField(verbose_name="命中倍率")),
                (
                    "is_bonus",
                    models.BooleanField(default=False, verbose_name="是否小暴击"),
                ),
                (
                    "is_jackpot",
                    models.BooleanField(default=False, verbose_name="是否大暴击"),
                ),
                (
                    "is_pity",
                    models.BooleanField(default=False, verbose_name="是否保底"),
                ),
            ],
            options={
                "verbose_name": "抽卡记录",
                "verbose_name_plural": "抽卡记录",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="GachaPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="卡池名称")),
                (
                    "cost_primary",
                    models.PositiveIntegerField(default=10, verbose_name="抽卡消耗"),
                ),
                (
                    "base_secondary_reward",
                    models.PositiveIntegerField(default=5, verbose_name="基础二级货币"),
                ),
                (
                    "bonus_rate",
                    models.FloatField(default=0.15, verbose_name="小暴击概率"),
                ),
                (
                    "jackpot_rate",
                    models.FloatField(default=0.03, verbose_name="大暴击概率"),
                ),
                (
                    "bonus_multiplier",
                    models.PositiveIntegerField(default=2, verbose_name="小暴击倍率"),
                ),
                (
                    "jackpot_multiplier",
                    models.PositiveIntegerField(default=5, verbose_name="大暴击倍率"),
                ),
                (
                    "pity_threshold",
                    models.PositiveIntegerField(default=10, verbose_name="保底阈值"),
                ),
                (
                    "pity_multiplier",
                    models.PositiveIntegerField(default=3, verbose_name="保底倍率"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "卡池",
                "verbose_name_plural": "卡池",
            },
        ),
    ]
