# Generated by Django 4.2.5 on 2026-04-17 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gacha", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gachadrawrecord",
            name="cost_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wallet.wallettransaction",
            ),
        ),
        migrations.AddField(
            model_name="gachadrawrecord",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gacha_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gachadrawrecord",
            name="pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="draw_records",
                to="gacha.gachapool",
            ),
        ),
        migrations.AddField(
            model_name="gachadrawrecord",
            name="reward_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wallet.wallettransaction",
            ),
        ),
    ]
