# Generated by Django 4.2.5 on 2026-05-08 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gacha", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gachadrawrecord",
            name="is_bonus",
        ),
        migrations.RemoveField(
            model_name="gachadrawrecord",
            name="is_jackpot",
        ),
        migrations.RemoveField(
            model_name="gachadrawrecord",
            name="is_pity",
        ),
        migrations.RemoveField(
            model_name="gachadrawrecord",
            name="multiplier",
        ),
        migrations.RemoveField(
            model_name="gachapool",
            name="base_secondary_reward",
        ),
        migrations.RemoveField(
            model_name="gachapool",
            name="bonus_multiplier",
        ),
        migrations.RemoveField(
            model_name="gachapool",
            name="bonus_rate",
        ),
        migrations.RemoveField(
            model_name="gachapool",
            name="jackpot_multiplier",
        ),
        migrations.RemoveField(
            model_name="gachapool",
            name="jackpot_rate",
        ),
        migrations.RemoveField(
            model_name="gachapool",
            name="pity_multiplier",
        ),
        migrations.RemoveField(
            model_name="gachapool",
            name="pity_threshold",
        ),
        migrations.AddField(
            model_name="gachadrawrecord",
            name="pity_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "无"),
                    ("rare", "优秀保底"),
                    ("epic", "暴击保底"),
                    ("legendary", "传说保底"),
                ],
                default="",
                max_length=16,
                verbose_name="触发的保底层级",
            ),
        ),
        migrations.AddField(
            model_name="gachadrawrecord",
            name="reward_tier",
            field=models.CharField(
                choices=[
                    ("common", "普通"),
                    ("rare", "优秀"),
                    ("epic", "暴击"),
                    ("legendary", "传说"),
                ],
                default="common",
                max_length=16,
                verbose_name="奖励档位",
            ),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="common_rate",
            field=models.FloatField(default=0.72, verbose_name="普通档概率"),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="common_reward",
            field=models.PositiveIntegerField(default=5, verbose_name="普通档奖励"),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="epic_pity_threshold",
            field=models.PositiveIntegerField(default=30, verbose_name="暴击保底阈值"),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="epic_rate",
            field=models.FloatField(default=0.06, verbose_name="暴击档概率"),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="epic_reward",
            field=models.PositiveIntegerField(default=40, verbose_name="暴击档奖励"),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="legendary_pity_threshold",
            field=models.PositiveIntegerField(default=80, verbose_name="传说保底阈值"),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="legendary_rate",
            field=models.FloatField(default=0.02, verbose_name="传说档概率"),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="legendary_reward",
            field=models.PositiveIntegerField(default=200, verbose_name="传说档奖励"),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="rare_pity_threshold",
            field=models.PositiveIntegerField(default=10, verbose_name="优秀保底阈值"),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="rare_rate",
            field=models.FloatField(default=0.2, verbose_name="优秀档概率"),
        ),
        migrations.AddField(
            model_name="gachapool",
            name="rare_reward",
            field=models.PositiveIntegerField(default=20, verbose_name="优秀档奖励"),
        ),
        migrations.AlterField(
            model_name="gachapool",
            name="cost_primary",
            field=models.PositiveIntegerField(
                default=50, verbose_name="抽卡消耗一级货币"
            ),
        ),
        migrations.CreateModel(
            name="GachaPoolUserState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "total_draws",
                    models.PositiveIntegerField(default=0, verbose_name="累计抽卡次数"),
                ),
                (
                    "draws_since_rare",
                    models.PositiveIntegerField(
                        default=0, verbose_name="距上次优秀及以上次数"
                    ),
                ),
                (
                    "draws_since_epic",
                    models.PositiveIntegerField(
                        default=0, verbose_name="距上次暴击及以上次数"
                    ),
                ),
                (
                    "draws_since_legendary",
                    models.PositiveIntegerField(
                        default=0, verbose_name="距上次传说次数"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gacha_pool_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_states",
                        to="gacha.gachapool",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户卡池状态",
                "verbose_name_plural": "用户卡池状态",
                "unique_together": {("owner", "pool")},
            },
        ),
    ]
