# Generated by Django 4.2.5 on 2026-04-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("terms", "用户服务协议"),
                            ("privacy", "隐私政策"),
                            ("data_collection", "个人信息收集清单"),
                            ("children", "未成年人说明"),
                        ],
                        max_length=32,
                        verbose_name="文档类型",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("version", models.CharField(max_length=32, verbose_name="版本号")),
                (
                    "summary",
                    models.CharField(blank=True, max_length=255, verbose_name="摘要"),
                ),
                ("content", models.TextField(verbose_name="正文")),
                ("effective_at", models.DateTimeField(verbose_name="生效时间")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "prompt_notes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="提示词补充信息"
                    ),
                ),
            ],
            options={
                "verbose_name": "法律与政策文档",
                "verbose_name_plural": "法律与政策文档",
                "ordering": ("document_type", "-effective_at", "-id"),
            },
        ),
    ]
