# Generated by Django 4.2.5 on 2026-04-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="头像"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=100, verbose_name="个人签名"),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="生日"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "男"), ("female", "女"), ("unknown", "未知")],
                default="unknown",
                max_length=16,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("employee", "上班族"),
                    ("student", "学生"),
                    ("teacher", "教师"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=16,
                verbose_name="职业",
            ),
        ),
    ]
