# Generated by Django 4.2.5 on 2026-04-29 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_user_bio_user_birth_date_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="basic_profile_completed",
            field=models.BooleanField(default=False, verbose_name="基础资料是否完善"),
        ),
        migrations.AddField(
            model_name="user",
            name="basic_profile_completion_score",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="基础资料完善度"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="basic_profile_last_prompted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="基础资料上次提醒时间"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="basic_profile_missing_fields",
            field=models.JSONField(
                blank=True, default=list, verbose_name="基础资料待补充字段"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="education_stage",
            field=models.CharField(
                choices=[
                    ("middle_school", "初中"),
                    ("high_school", "高中"),
                    ("college", "本科/大专"),
                    ("graduate", "研究生"),
                    ("working", "已工作"),
                    ("other", "其他"),
                    ("undisclosed", "暂不填写"),
                ],
                default="undisclosed",
                max_length=24,
                verbose_name="教育阶段",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="focus_areas",
            field=models.JSONField(
                blank=True, default=list, verbose_name="当前主要关注领域"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language_preference",
            field=models.CharField(
                choices=[
                    ("zh-hans", "简体中文"),
                    ("en", "English"),
                    ("bilingual", "中英双语"),
                    ("other", "其他"),
                    ("undisclosed", "暂不填写"),
                ],
                default="zh-hans",
                max_length=24,
                verbose_name="语言偏好",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="long_term_goals",
            field=models.JSONField(
                blank=True, default=list, verbose_name="长期目标类型"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(blank=True, max_length=80, verbose_name="所在地区"),
        ),
        migrations.AlterField(
            model_name="user",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("student", "学生"),
                    ("employee", "上班族"),
                    ("teacher", "教师"),
                    ("freelancer", "自由职业"),
                    ("creator", "创作者"),
                    ("job_seeker", "求职中"),
                    ("homemaker", "居家/照护者"),
                    ("retired", "退休"),
                    ("other", "其他"),
                    ("undisclosed", "暂不填写"),
                ],
                default="undisclosed",
                max_length=24,
                verbose_name="职业",
            ),
        ),
        migrations.CreateModel(
            name="StableProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "self_management_challenges",
                    models.JSONField(
                        blank=True, default=list, verbose_name="自我管理难点"
                    ),
                ),
                (
                    "motivation_preferences",
                    models.JSONField(
                        blank=True, default=list, verbose_name="动机来源偏好"
                    ),
                ),
                (
                    "reward_preference",
                    models.CharField(
                        choices=[
                            ("instant", "偏好即时奖励"),
                            ("big_later", "偏好延迟大奖励"),
                            ("balanced", "二者平衡"),
                            ("undisclosed", "暂不填写"),
                        ],
                        default="undisclosed",
                        max_length=24,
                        verbose_name="奖励偏好",
                    ),
                ),
                (
                    "penalty_tolerance",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("undisclosed", "暂不填写"),
                        ],
                        default="undisclosed",
                        max_length=24,
                        verbose_name="惩罚接受度",
                    ),
                ),
                (
                    "stress_sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("undisclosed", "暂不填写"),
                        ],
                        default="undisclosed",
                        max_length=24,
                        verbose_name="压力敏感度",
                    ),
                ),
                (
                    "self_discipline_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="自律自评分"
                    ),
                ),
                (
                    "chronotype",
                    models.CharField(
                        choices=[
                            ("morning", "早型"),
                            ("night", "晚型"),
                            ("flexible", "不固定"),
                            ("undisclosed", "暂不填写"),
                        ],
                        default="undisclosed",
                        max_length=24,
                        verbose_name="作息类型",
                    ),
                ),
                (
                    "energy_peak_periods",
                    models.JSONField(
                        blank=True, default=list, verbose_name="精力高峰时段"
                    ),
                ),
                (
                    "task_granularity_preference",
                    models.CharField(
                        choices=[
                            ("small", "喜欢拆小任务"),
                            ("balanced", "大小任务都可以"),
                            ("large", "偏好大块任务"),
                            ("undisclosed", "暂不填写"),
                        ],
                        default="undisclosed",
                        max_length=24,
                        verbose_name="偏好任务粒度",
                    ),
                ),
                (
                    "planning_style_preference",
                    models.CharField(
                        choices=[
                            ("structured", "严格计划"),
                            ("flexible", "弹性计划"),
                            ("mixed", "两者结合"),
                            ("undisclosed", "暂不填写"),
                        ],
                        default="undisclosed",
                        max_length=24,
                        verbose_name="计划风格偏好",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="稳定画像是否完成"),
                ),
                (
                    "completion_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="稳定画像完善度"
                    ),
                ),
                (
                    "missing_fields",
                    models.JSONField(
                        blank=True, default=list, verbose_name="稳定画像待补充字段"
                    ),
                ),
                (
                    "last_prompted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="稳定画像上次提醒时间"
                    ),
                ),
                (
                    "questionnaire_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="问卷完成时间"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stable_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "稳定画像",
                "verbose_name_plural": "稳定画像",
            },
        ),
        migrations.CreateModel(
            name="DynamicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "current_stage_tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="当前阶段标签"
                    ),
                ),
                (
                    "stress_level",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="最近压力水平"
                    ),
                ),
                (
                    "sleep_quality",
                    models.CharField(
                        choices=[
                            ("low", "低/较差"),
                            ("medium", "一般"),
                            ("high", "高/较好"),
                            ("undisclosed", "暂不填写"),
                        ],
                        default="undisclosed",
                        max_length=24,
                        verbose_name="最近睡眠情况",
                    ),
                ),
                (
                    "mood_state",
                    models.CharField(
                        choices=[
                            ("low", "低/较差"),
                            ("medium", "一般"),
                            ("high", "高/较好"),
                            ("undisclosed", "暂不填写"),
                        ],
                        default="undisclosed",
                        max_length=24,
                        verbose_name="最近情绪状态",
                    ),
                ),
                (
                    "available_time_level",
                    models.CharField(
                        choices=[
                            ("limited", "很少"),
                            ("normal", "一般"),
                            ("ample", "充足"),
                            ("undisclosed", "暂不填写"),
                        ],
                        default="undisclosed",
                        max_length=24,
                        verbose_name="最近可支配时间",
                    ),
                ),
                (
                    "current_top_goal",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="当前最重要目标"
                    ),
                ),
                (
                    "current_main_blocker",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="当前最大阻碍"
                    ),
                ),
                (
                    "weekly_time_budget_hours",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="本周可投入时长"
                    ),
                ),
                (
                    "last_prompted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="动态状态上次提醒时间"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "动态状态画像",
                "verbose_name_plural": "动态状态画像",
            },
        ),
    ]
