# Generated by Django 4.2.5 on 2026-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_basic_profile_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="experience",
            field=models.PositiveIntegerField(default=0, verbose_name="当前等级经验"),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.PositiveIntegerField(default=1, verbose_name="用户等级"),
        ),
        migrations.AddField(
            model_name="user",
            name="total_experience",
            field=models.PositiveIntegerField(default=0, verbose_name="累计经验"),
        ),
    ]
