# Generated by Django 4.2.5 on 2026-06-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_experience_user_level_user_total_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("password_reset", "Password reset"),
                        ],
                        max_length=32,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("sent_ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Email verification code",
                "verbose_name_plural": "Email verification codes",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "created_at"],
                        name="users_email_email_b72057_idx",
                    ),
                    models.Index(
                        fields=["email", "purpose", "used_at"],
                        name="users_email_email_cae494_idx",
                    ),
                ],
            },
        ),
    ]
