# Generated by Django 4.2.5 on 2026-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIReportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("daily", "日报"), ("monthly", "月报")], max_length=20
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="报告摘要")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待生成"),
                            ("done", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("prompt_context", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "AI报告任务",
                "verbose_name_plural": "AI报告任务",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
