# Generated by Django 4.2.5 on 2026-04-25 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aireportjob",
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "AI 报告任务",
                "verbose_name_plural": "AI 报告任务",
            },
        ),
        migrations.CreateModel(
            name="AIAgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "workflow_key",
                    models.CharField(max_length=64, verbose_name="工作流标识"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("succeeded", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "input_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="输入参数"),
                ),
                (
                    "context_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="上下文快照"
                    ),
                ),
                (
                    "state_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="状态数据"),
                ),
                (
                    "result_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="输出结果"),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="错误信息"
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="追踪标识"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Agent 运行记录",
                "verbose_name_plural": "AI Agent 运行记录",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
