# Generated by Django 4.2.5 on 2026-05-12 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_difficulty_level_task_estimated_focus_minutes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AITaskPricingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting_feedback", "等待反馈"),
                            ("accepted", "已接受"),
                            ("cancelled", "已取消"),
                            ("failed", "失败"),
                        ],
                        default="waiting_feedback",
                        max_length=32,
                    ),
                ),
                (
                    "task_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="任务草稿"),
                ),
                (
                    "profile_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="用户画像快照"
                    ),
                ),
                (
                    "pricing_standard_version",
                    models.CharField(default="task_pricing_v1", max_length=32),
                ),
                (
                    "pricing_standard_excerpt",
                    models.TextField(blank=True, verbose_name="定价标准摘录"),
                ),
                (
                    "quote_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="当前定价"),
                ),
                (
                    "feedback_history",
                    models.JSONField(blank=True, default=list, verbose_name="反馈历史"),
                ),
                (
                    "dynamic_profile_update",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="动态画像更新"
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=255)),
                (
                    "created_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_sessions",
                        to="tasks.task",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_task_pricing_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI任务定价会话",
                "verbose_name_plural": "AI任务定价会话",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
