# Generated by Django 4.2.5 on 2026-06-06 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_public_shop_items_and_active_effects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0004_merge_20260513_aitaskpricing_agentrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIWishPricingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "用户手动愿望"),
                            ("daily_refresh", "每日刷新愿望"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting_confirmation", "等待确认"),
                            ("accepted", "已接受"),
                            ("cancelled", "已取消"),
                            ("failed", "失败"),
                        ],
                        default="waiting_confirmation",
                        max_length=32,
                    ),
                ),
                (
                    "refresh_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="刷新日期"
                    ),
                ),
                (
                    "wish_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="愿望草稿"),
                ),
                (
                    "context_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="上下文快照"
                    ),
                ),
                (
                    "profile_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="用户画像快照"
                    ),
                ),
                (
                    "pricing_standard_version",
                    models.CharField(default="wish_pricing_v1", max_length=32),
                ),
                (
                    "pricing_standard_excerpt",
                    models.TextField(blank=True, verbose_name="定价标准摘录"),
                ),
                (
                    "quote_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="当前定价"),
                ),
                ("error_message", models.CharField(blank=True, max_length=255)),
                (
                    "generated_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wish_pricing_sessions",
                        to="shop.wishitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_wish_pricing_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI愿望定价会话",
                "verbose_name_plural": "AI愿望定价会话",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="aiwishpricingsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("refresh_date__isnull", False), ("source", "daily_refresh")
                ),
                fields=("owner", "source", "refresh_date"),
                name="unique_daily_wish_refresh_per_user_date",
            ),
        ),
    ]
