# Generated by Django 4.2.5 on 2026-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RedemptionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cost_secondary",
                    models.PositiveIntegerField(verbose_name="消耗二级货币"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "待处理"),
                            ("fulfilled", "已兑现"),
                            ("rejected", "已拒绝"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "兑换记录",
                "verbose_name_plural": "兑换记录",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="WishItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=120, verbose_name="愿望名称")),
                ("description", models.TextField(blank=True, verbose_name="愿望描述")),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "用户创建"), ("system", "系统推荐")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "price_secondary",
                    models.PositiveIntegerField(verbose_name="二级货币定价"),
                ),
                (
                    "inventory",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="库存"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
                (
                    "ai_pricing",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="AI定价数据"
                    ),
                ),
            ],
            options={
                "verbose_name": "愿望商品",
                "verbose_name_plural": "愿望商品",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
