# Generated by Django 4.2.5 on 2026-05-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_wallettransaction_reason"),
        ("shop", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redemptionrecord",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="兑现时间"),
        ),
        migrations.AddField(
            model_name="redemptionrecord",
            name="refund_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wallet.wallettransaction",
            ),
        ),
        migrations.AddField(
            model_name="redemptionrecord",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="拒绝时间"),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="auto_refund_on_reject",
            field=models.BooleanField(default=True, verbose_name="拒绝时自动退款"),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="price_tier",
            field=models.CharField(
                choices=[
                    ("small", "小愿望"),
                    ("medium", "中愿望"),
                    ("large", "大愿望"),
                ],
                default="medium",
                max_length=16,
                verbose_name="价格档位",
            ),
        ),
        migrations.AlterField(
            model_name="wishitem",
            name="ai_pricing",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="AI 定价数据"
            ),
        ),
    ]
