# Generated by Django 4.2.5 on 2026-05-09 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0003_redemptionrecord_fulfilled_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishitem",
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "商店商品",
                "verbose_name_plural": "商店商品",
            },
        ),
        migrations.AddField(
            model_name="redemptionrecord",
            name="effect_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="效果快照"),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("growth_material", "养成材料"),
                    ("utility_item", "功能轻道具"),
                    ("wish_reward", "愿望奖励"),
                ],
                default="wish_reward",
                max_length=32,
                verbose_name="商品大类",
            ),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="effect_payload",
            field=models.JSONField(blank=True, default=dict, verbose_name="效果配置"),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="is_stackable",
            field=models.BooleanField(default=True, verbose_name="是否可叠加持有"),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="item_kind",
            field=models.CharField(
                choices=[
                    ("experience_pack", "经验材料"),
                    ("debt_repayment_card", "还债卡"),
                    ("task_failure_protection_card", "任务失败保护卡"),
                    ("indulgence_day_card", "放纵日卡"),
                    ("wish", "愿望"),
                ],
                default="wish",
                max_length=40,
                verbose_name="商品类型",
            ),
        ),
        migrations.AddField(
            model_name="wishitem",
            name="rarity",
            field=models.CharField(
                choices=[("common", "普通"), ("rare", "稀有"), ("epic", "珍贵")],
                default="common",
                max_length=16,
                verbose_name="稀有度",
            ),
        ),
        migrations.AlterField(
            model_name="redemptionrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "待处理"),
                    ("completed", "已完成"),
                    ("fulfilled", "已兑现"),
                    ("rejected", "已拒绝"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wishitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="商品描述"),
        ),
        migrations.AlterField(
            model_name="wishitem",
            name="price_tier",
            field=models.CharField(
                choices=[("small", "小型"), ("medium", "中型"), ("large", "大型")],
                default="medium",
                max_length=16,
                verbose_name="价格档位",
            ),
        ),
        migrations.AlterField(
            model_name="wishitem",
            name="title",
            field=models.CharField(max_length=120, verbose_name="商品名称"),
        ),
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="持有数量"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_records",
                        to="shop.wishitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户道具库存",
                "verbose_name_plural": "用户道具库存",
                "ordering": ("-updated_at", "-id"),
                "unique_together": {("owner", "item")},
            },
        ),
    ]
