# Generated by Django 4.2.5 on 2026-05-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_wishitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishitem",
            name="catalog_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="目录键"
            ),
        ),
    ]
