# Generated by Django 4.2.5 on 2026-06-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0006_seed_default_shop_items"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1
                                FROM information_schema.columns
                                WHERE table_name = 'shop_wishitem' AND column_name = 'item_kind'
                            ) THEN
                                EXECUTE '
                                    UPDATE shop_wishitem
                                    SET category = item_kind
                                    WHERE item_kind IN (
                                        ''experience_pack'',
                                        ''debt_repayment_card'',
                                        ''task_failure_protection_card'',
                                        ''indulgence_day_card'',
                                        ''wish''
                                    )
                                ';
                            END IF;
                        END
                        $$;

                        UPDATE shop_wishitem
                        SET category = CASE
                            WHEN catalog_key LIKE 'exp_pack_%' THEN 'experience_pack'
                            WHEN catalog_key = 'debt_repayment_card_standard' THEN 'debt_repayment_card'
                            WHEN catalog_key = 'task_failure_protection_card' THEN 'task_failure_protection_card'
                            WHEN catalog_key = 'indulgence_day_card' THEN 'indulgence_day_card'
                            WHEN category = 'wish_reward' THEN 'wish'
                            ELSE category
                        END;

                        ALTER TABLE shop_wishitem DROP COLUMN IF EXISTS ai_pricing;
                        ALTER TABLE shop_wishitem DROP COLUMN IF EXISTS item_kind;
                        ALTER TABLE shop_wishitem DROP COLUMN IF EXISTS source;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name="wishitem", name="ai_pricing"),
                migrations.RemoveField(model_name="wishitem", name="item_kind"),
                migrations.RemoveField(model_name="wishitem", name="source"),
            ],
        ),
        migrations.AlterField(
            model_name="wishitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("experience_pack", "经验材料"),
                    ("debt_repayment_card", "还债卡"),
                    ("task_failure_protection_card", "任务失败保护卡"),
                    ("indulgence_day_card", "放纵日卡"),
                    ("wish", "愿望奖励"),
                ],
                default="wish",
                max_length=40,
                verbose_name="商品分类",
            ),
        ),
        migrations.AlterField(
            model_name="wishitem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wish_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
        migrations.CreateModel(
            name="UserActiveEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("effect_type", models.CharField(max_length=50, verbose_name="效果类型")),
                ("starts_at", models.DateTimeField(verbose_name="开始时间")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                ("remaining_uses", models.IntegerField(default=-1, verbose_name="剩余使用次数")),
                ("effect_payload", models.JSONField(blank=True, default=dict, verbose_name="效果附加负载")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_effects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="拥有者",
                    ),
                ),
                (
                    "source_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.wishitem",
                        verbose_name="来源道具",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户有效效果/Buff",
                "verbose_name_plural": "用户有效效果/Buff",
                "ordering": ("-created_at",),
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE UNIQUE INDEX IF NOT EXISTS unique_public_wish_item_catalog_key
                        ON shop_wishitem (catalog_key)
                        WHERE owner_id IS NULL AND NOT (catalog_key = '');
                    """,
                    reverse_sql="DROP INDEX IF EXISTS unique_public_wish_item_catalog_key;",
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="wishitem",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(owner__isnull=True) & ~models.Q(catalog_key=""),
                        fields=("catalog_key",),
                        name="unique_public_wish_item_catalog_key",
                    ),
                ),
            ],
        ),
    ]
