# Generated by Django 4.2.5 on 2026-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_seed_default_shop_items"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wishitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("catalog_key", ""), _negated=True),
                fields=("owner", "catalog_key"),
                name="uniq_shop_item_owner_catalog_key_nonempty",
            ),
        ),
    ]
