# Generated by Django 4.2.5 on 2026-04-17 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "primary_balance",
                    models.PositiveIntegerField(default=0, verbose_name="一级货币余额"),
                ),
                (
                    "secondary_balance",
                    models.PositiveIntegerField(default=0, verbose_name="二级货币余额"),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "钱包",
                "verbose_name_plural": "钱包",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "currency_type",
                    models.CharField(
                        choices=[("primary", "一级货币"), ("secondary", "二级货币")],
                        max_length=20,
                        verbose_name="货币类型",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("task_reward", "任务奖励"),
                            ("task_penalty", "任务惩罚"),
                            ("gacha_cost", "抽卡消耗"),
                            ("gacha_reward", "抽卡奖励"),
                            ("shop_redeem", "商店兑换"),
                            ("manual_adjust", "后台调整"),
                        ],
                        max_length=32,
                        verbose_name="交易原因",
                    ),
                ),
                ("delta", models.IntegerField(verbose_name="变动值")),
                (
                    "balance_before",
                    models.PositiveIntegerField(verbose_name="变更前余额"),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(verbose_name="变更后余额"),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="引用对象类型"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="引用对象ID"
                    ),
                ),
                (
                    "memo",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "钱包流水",
                "verbose_name_plural": "钱包流水",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
