# Generated by Django 4.2.5 on 2026-05-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="primary_balance",
            field=models.IntegerField(default=0, verbose_name="一级货币余额"),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="balance_after",
            field=models.IntegerField(verbose_name="变更后余额"),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="balance_before",
            field=models.IntegerField(verbose_name="变更前余额"),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="reason",
            field=models.CharField(
                choices=[
                    ("task_reward", "任务奖励"),
                    ("task_penalty", "任务惩罚"),
                    ("gacha_cost", "抽卡消耗"),
                    ("gacha_reward", "抽卡奖励"),
                    ("shop_redeem", "商店兑换"),
                    ("manual_adjust", "后台调整"),
                    ("debt_reset", "债务重置"),
                ],
                max_length=32,
                verbose_name="交易原因",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="reference_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="引用对象 ID"
            ),
        ),
    ]
