# Generated by Django 4.2.5 on 2026-05-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallet_primary_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="reason",
            field=models.CharField(
                choices=[
                    ("task_reward", "任务奖励"),
                    ("task_penalty", "任务惩罚"),
                    ("gacha_cost", "抽卡消耗"),
                    ("gacha_reward", "抽卡奖励"),
                    ("shop_redeem", "商店兑换"),
                    ("shop_refund", "商店退款"),
                    ("manual_adjust", "后台调整"),
                    ("debt_reset", "债务重置"),
                ],
                max_length=32,
                verbose_name="交易原因",
            ),
        ),
    ]
