# Generated by Django 4.2.5 on 2026-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=120, verbose_name="任务标题")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("daily", "日常任务"),
                            ("recurring", "周期任务"),
                            ("one_time", "一次性任务"),
                        ],
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "不重复"),
                            ("daily", "每天"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True, default=list, verbose_name="周重复设置"
                    ),
                ),
                (
                    "month_days",
                    models.JSONField(
                        blank=True, default=list, verbose_name="月重复设置"
                    ),
                ),
                (
                    "metric_key",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="系统指标键"
                    ),
                ),
                (
                    "target_value",
                    models.IntegerField(blank=True, null=True, verbose_name="目标值"),
                ),
                (
                    "progress_target",
                    models.PositiveIntegerField(default=100, verbose_name="进度目标"),
                ),
                (
                    "reward_primary",
                    models.PositiveIntegerField(default=0, verbose_name="一级货币奖励"),
                ),
                (
                    "penalty_primary",
                    models.PositiveIntegerField(default=0, verbose_name="一级货币惩罚"),
                ),
                (
                    "starts_on",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "ends_on",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("archived", "归档")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "ai_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="AI评估数据"
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="TaskOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("occurrence_date", models.DateField(verbose_name="发生日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待完成"),
                            ("completed", "已完成"),
                            ("missed", "已错过"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(default=0, verbose_name="完成进度"),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结算时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "任务实例",
                "verbose_name_plural": "任务实例",
                "ordering": ("-occurrence_date", "-id"),
            },
        ),
    ]
