# Generated by Django 4.2.5 on 2026-05-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="difficulty_level",
            field=models.CharField(
                choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                default="medium",
                max_length=16,
                verbose_name="难度等级",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_focus_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="预估专注时长（分钟）"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="pricing_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="发起定价时间"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="pricing_resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="完成定价时间"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="pricing_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="定价快照"),
        ),
        migrations.AddField(
            model_name="task",
            name="pricing_status",
            field=models.CharField(
                choices=[
                    ("unpriced", "未定价"),
                    ("pending", "待 AI 定价"),
                    ("quoted", "已生成报价"),
                    ("applied", "已应用报价"),
                ],
                default="unpriced",
                max_length=20,
                verbose_name="定价状态",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="settlement_track",
            field=models.CharField(
                choices=[("regular", "常规轨道"), ("exploration", "探索轨道")],
                default="regular",
                max_length=20,
                verbose_name="结算轨道",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="ai_metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="AI 元数据"),
        ),
    ]
