# Generated by Django 4.2.5 on 2026-06-05 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0003_alter_wallettransaction_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetricSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "window_type",
                    models.CharField(
                        choices=[
                            ("recent_7d_30d", "Recent 7-30 days"),
                            ("monthly_30d_1y", "Monthly 30 days to 1 year"),
                        ],
                        max_length=32,
                    ),
                ),
                ("bucket_start", models.DateField(db_index=True)),
                ("bucket_end", models.DateField(db_index=True)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("summary_text", models.TextField(blank=True)),
                ("summary_payload", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metric_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-bucket_end", "-id"),
                "unique_together": {
                    ("owner", "window_type", "bucket_start", "bucket_end")
                },
            },
        ),
        migrations.CreateModel(
            name="DailyMetricRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("record_date", models.DateField(db_index=True)),
                ("wake_time", models.TimeField()),
                ("sleep_time", models.TimeField()),
                ("phone_minutes", models.PositiveIntegerField(default=0)),
                ("water_cups", models.PositiveSmallIntegerField(default=0)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("reward_primary", models.PositiveIntegerField(default=0)),
                ("agent_feedback", models.TextField(blank=True)),
                ("profile_snapshot", models.JSONField(blank=True, default=dict)),
                ("history_snapshot", models.JSONField(blank=True, default=dict)),
                ("agent_payload", models.JSONField(blank=True, default=dict)),
                (
                    "detail_level",
                    models.CharField(
                        choices=[("detailed", "Detailed"), ("reduced", "Reduced")],
                        default="detailed",
                        max_length=16,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metric_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reward_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wallet.wallettransaction",
                    ),
                ),
            ],
            options={
                "ordering": ("-record_date", "-id"),
                "unique_together": {("owner", "record_date")},
            },
        ),
    ]
